### ISSUE TITLE
%TypedArrayPrototype%.toJSON

### ISSUE THREAD

**Issue by zloirock** [DavidBruant/Map-Set.prototype.toJSON#13]
Currently, we haven't `%TypedArrayPrototype%.toJSON` or special case for typed arrays in `JSON.stringify`. Result of `JSON.stringify` on typed arrays isn't very useful:

``` js
JSON.stringify(new Uint8Array([1, 2, 3, 4])); // => '{"0":1,"1":2,"2":3,"3":4}'
```

Typed array - also collections, added in ES6, like `Map` ans `Set`. Maybe makes sense add `%TypedArrayPrototype%.toJSON` as a part of this proposal?

**Comment by ljharb** [comment]
Typed Arrays are a performance feature, and while they should have parity with Arrays, they don't have parity with Map/Set. This could be a useful proposal to bring separately, but I don't think it should be bundled in as it will likely have different kinds of bikeshedding and discussion, and the use cases are different.
