### ISSUE TITLE
Look up Symbol.iterator?

### ISSUE THREAD

**Issue by ljharb** [DavidBruant/Map-Set.prototype.toJSON#14]
Instead of making these different functions, one of which is hardcoded to "entries" and one to "values", another alternative would be using the same function value (`===`) which basically did `return [...this];`, ie, looked up `this[Symbol.iterator]`.

This can be done by modifying step 2 to be "Let _items_ be GetIterator(_M_)" (and then deleting one of the method definitions, and pointing it to be `===` to the other one, similarly to http://tc39.github.io/ecma262/#sec-array.prototype-@@iterator).

**Comment by matjaz** [comment]
:+1: 

``` js
Set.prototype.toJSON = function toJSON() {
  return [...this];
}
```

**Comment by ljharb** [comment]
@DavidBruant what are your thoughts on this approach?

**Comment by DavidBruant** [comment]
I love it. Among other things, it opens up the possibility for any iterable to use the exact same `.toJSON` function.
