### ISSUE TITLE
Proposal rejected.

### ISSUE THREAD

**Issue by ljharb** [DavidBruant/Map-Set.prototype.toJSON#16]
In the March 2016 TC39 meeting, I brought this proposal to the committee.

It was thoroughly rejected, for a number of reasons. Primarily, that `toJSON` is a legacy artifact, and a better approach is to use a custom `replacer` that, for example, checks `[Symbol.toStringTag]` and dispatches to appropriate serializations.

In addition, the committee did not want to bless the `toJSON` approach by adding what would be an incomplete representation - one that would not obviate the need for developers to define their own serialization format and revivification logic.

(https://github.com/tc39/ecma262/pull/506)

**Comment by DavidBruant** [comment]
Sounds good, thanks for all the time you spent on this @ljharb and @zloirock ! :-)
