### ISSUE TITLE
Why not create an object instead of array for Map?

### ISSUE THREAD

**Issue by hgoebl** [DavidBruant/Map-Set.prototype.toJSON#17]
```
Map.prototype.toJSON = function toJSON() {
    let map = {};
    for (let entry of Map.prototype.entries.call(this)) {
        let [key, value] = entry;
        map[key] = value;
    }
    return map;
};
```
At least it's easier to wade through this instead of arrays of arrays.
If `key` -> string is not unique, it's always a problem for receiver to interpret the resulting JSON.

**Comment by ljharb** [comment]
Because Maps can have object keys, but objects can only have string and Symbol keys.

Also, a Map could have both `1` and `'1'` as keys - which would parse fine as arrays of entries, but needlessly overwrite one another as object keys.
