### ISSUE TITLE
Why JSON.stringify() shouldn't be updated to support Iteratables?

### ISSUE THREAD

**Issue by mohsen1** [DavidBruant/Map-Set.prototype.toJSON#7]
Pardon my misunderstanding if that's the case. Why we should add a `toJSON` method to Maps and Sets instead of updating `JSON.stringify` to support iteratables so not only Map and Set can be stringified but also any custom class that is iteratable can be stringified. 

This also helps with my proposal for [async JSON methods](https://github.com/mohsen1/async-json). If JSON stringify supports map then we can stringify Maps asynchronously.

**Comment by ljharb** [comment]
JSON.stringify supporting iterables would likely be a breaking change.

**Comment by DavidBruant** [comment]
Very specifically, there is a risk some websites on the web doing `JSON.stringify(document.querySelectorAll(someSelector))`. If JSON.stringify behavior changes to support iterators, such code may break. No browser will take the risk, etc. the usual business.

Maybe a different idea is to add support to JSON.stringify to Maps and Sets specifically.

**Comment by mohsen1** [comment]
One interesting related issue is YAML. YAML does support maps and [it's a problem](https://github.com/nodeca/js-yaml#caveats) when we want to convert it to JSON.

**Comment by ljharb** [comment]
Any custom "class"/object can already be stringified by adding a `toJSON` method - that's the official way to do custom JSON serialization - which is why adding `toJSON` to `Map`/`Set` is the appropriate proposal.

**Comment by mohsen1** [comment]
Is that part of any spec? Is there a specific global Symbol for that?

**Comment by ljharb** [comment]
There's no symbols, it's a string property. It's been part of the JS spec since ES5, yes.

**Comment by mohsen1** [comment]
Thanks!
