### ISSUE TITLE
serialization for Map

### ISSUE THREAD

**Issue by sonnyp** [DavidBruant/Map-Set.prototype.toJSON#8]
Hi @DavidBruant :wave:

I wonder what's the motivation for serializing Map as an array of k/v pairs instead of an object.
I got a bit surprised by this behavior https://github.com/babel/babel/issues/2217

If a key is not a string then it can be discarded like undefined values.

**Comment by zloirock** [comment]
[By spec](http://www.ecma-international.org/ecma-262/6.0/#sec-map-objects)

> Map objects are collections of **key/value pairs** where **both the keys and values may be arbitrary ECMAScript language values**.

I don't see any reason why key - valid JSON value should be discarded.

**Comment by sonnyp** [comment]
If not discarded stringified then my point being Map should serialize as JSON object.

**Comment by zloirock** [comment]
See #1, I proposed this solution too, but current behavior looks more convenient.

**Comment by ljharb** [comment]
JSON is inherently limited to a subset of the values available in JS. The purpose of the `toJSON` method, imo, is not to remove functions for example (that's the responsibility of the JSON stringifier itself), but to produce as useful a serializable representation of the object as possible.

An array of entries, without any filtering of any kind, seems to me to be both the most useful, and most appropriate separation of responsibilities, for `Map#toJSON`. The same applies to `Set#toJSON` - where it produces an array of values, but does not concern itself whether those values are themselves serializable to JSON.

**Comment by sonnyp** [comment]
Thinking twice I don't think Map and Set prototypes should have a toJSON property at all.

The problem with toJSON is that even with a replacer method on JSON.stringify there is no way of telling if the object being serialized is a map because it is the result of the toJSON function that will be passed to the replacer; not the original object. So there would be no way to choose how to serialize Map/Set which we can agree here is not that straightforward (at least for Map).

The alternative for users would be to
- change the toJSON method on the Map and Set prototypes but that would be a bad practice
- extend Map.protoype, define a toJSON property and serialize the instances but that's not always an option

**Comment by ljharb** [comment]
Subclassing `Map` would be the way to go I think. Why would you need to know how to serialize `Map`/`Set` as different from entries and values? A `Set` should be indistinguishable from an array when serialized anyways.

**Comment by DavidBruant** [comment]
Hi @sonnyp :-)

Before #5, the serialization of Map was an object. I got convinced to change my mind at https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/1#issuecomment-94268032

> Thinking twice I don't think Map and Set prototypes should have a toJSON property at all.

Currently, calling `JSON.stringify` on Maps and Sets returns `{}` which is a bit ridiculous. Fixing this is the original motivation for this proposal to ES.next.
Granted, the current solution might not be perfect in the sense that it looses a bit of information (that the serialized object was a Map, not an object and a Set, not an array) but it sounds like an acceptable trade-off especially given it's easy to re-instantiate Maps and Sets from the JSON form.

> The alternative for users would be to

Another alternative would be to add your own `toJSON` as own property of the Map and Set with a mixin or else.

``` js
function specificMapToJSON(){}
var toJSONMixin = {toJSON: specificMapToJSON};

var myMap = Object.assign(new Map(initValues), toJSONMixin);
```

**Comment by letmaik** [comment]
@sonnyp I fully agree with what you observed. I just stumbled over this by accident: https://github.com/zloirock/core-js/issues/148#issuecomment-164759122 And I have not found an easy way (except killing toJSON on the prototype) to transform Map instances in arbitrary object trees using my own logic, since they are not detectable anymore as such as you pointed out. I'm not sure if this is the fault of toJSON or rather of the stringify algorithm which possibly should give you the original value as well in the replacer function.

**Comment by ljharb** [comment]
The proper way is to attach your own `.toJSON` to the instances you want to transform differently.

**Comment by letmaik** [comment]
Really? It sounds more like a work around. And still for arbitrary objects I would have to scan the hierarchy and attach those .toJSON functions everywhere, and probably clone the whole object before-hand if I want to keep using it afterwards. This does not seem straighforward to me.

**Comment by ljharb** [comment]
Per https://github.com/zloirock/core-js/issues/148#issuecomment-164831510, you should be using a subclass of `Map` which then would only require one `toJSON` function on its prototype.

**Comment by ljharb** [comment]
I'm going to close this issue for now.
