### ISSUE TITLE
Next steps to propose at TC39 meeting?

### ISSUE THREAD

**Issue by ljharb** [DavidBruant/Map-Set.prototype.toJSON#9]
- Proposal is listed on https://github.com/tc39/ecma262/blob/master/stage0.md
- spec text is written https://github.com/DavidBruant/Map-Set.prototype.toJSON/blob/master/spec.md
- polyfills exist https://www.npmjs.com/package/map-tojson and https://www.npmjs.com/package/set-tojson
- Do you have a champion? It can't be me just yet.

The next meeting is in September. If you can find a champion and prepare a presentation, it'd be great to advance this to stage 1 or 2 at the next meeting!

**Comment by ljharb** [comment]
Looks like this didn't make it in time for the September meeting.

Have you found a champion that could present it at the November meeting?

**Comment by DavidBruant** [comment]
Last month, I emailed twice es-discuss and my messages never reached the list (?). I emailed privately a good share of TC39, but learned that some folks received the email in their spam. I have to admit I gave up afterwards :-/

**Comment by ljharb** [comment]
Let's give it another shot, I'd love to advocate for this at the next meeting and be an official spec reviewer (required for stage 2 → 3 progression) if you can locate a champion.

**Comment by ljharb** [comment]
@DavidBruant have you been able to find a champion? If not, I may be willing to take this on.

**Comment by DavidBruant** [comment]
> @DavidBruant have you been able to find a champion? If not, I may be willing to take this on.

I haven't yet. I didn't try after what I describe in https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/9#issuecomment-143208891

**Comment by ljharb** [comment]
I've added this proposal to the agenda for this week https://github.com/tc39/agendas/pull/171

**Comment by DavidBruant** [comment]
@ljharb  I am grateful that you're taking this to the TC39 meeting.
